[build]
  base = "/"
  command = "cd frontend && pnpm install && pnpm build"
  publish = "frontend/dist"
  functions = "frontend/netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "vite"
  targetPort = 5173

[functions]
  node_bundler = "esbuild"