name: Complete GitHub check
description: Complete a GitHub check run based on a step outcome

inputs:
  check_id:
    description: ID of the check run to update
    required: true
  check_outcome:
    description: Outcome of the step (success, failure, cancelled, skipped)
    required: true
    
runs:
  using: composite
  steps:
    - uses: actions/github-script@v8
      with:
        script: |
          const conclusion = '${{ inputs.check_outcome }}' === 'success' ? 'success' : 'failure';
          await github.rest.checks.update({
            owner: context.repo.owner,
            repo: context.repo.repo,
            check_run_id: parseInt('${{ inputs.check_id }}'),
            status: 'completed',
            conclusion: conclusion
          });

