"""
Initial migration: create all tables for SQLModelDataLayer
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0001_create_tables'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # This will be auto-generated by Alembic's autogenerate feature,
    # but for best practice, you can start with an empty upgrade and run autogenerate.
    pass

def downgrade():
    # Drop all tables (if needed)
    pass
