name: Install Node, pnpm and dependencies.
description: Install Node, pnpm and dependencies using cache.

inputs:
  node-version:
    description: Node.js version
    required: true
    default: 'lts/*'

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        run_install: false
    - name: Use Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: 'https://registry.npmjs.org'
        cache: 'pnpm'
        cache-dependency-path: '**/pnpm-lock.yaml'
    - name: Install JS dependencies
      run: pnpm install
      shell: bash