name: Mypy

on: [workflow_call]

jobs:
  mypy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        run: pipx install poetry
      - name: Set up Python
        id: python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: poetry
          cache-dependency-path: backend/poetry.lock
      - name: Set Poetry environment
        run: poetry env use '${{ steps.python.outputs.python-path }}'
      - name: Install dependencies
        run: poetry install --with tests --with mypy --with custom-data
      - name: Run Mypy
        run: poetry run mypy chainlit/
