name: Mypy

on: [workflow_call]

permissions: read-all

jobs:
  mypy:
    runs-on: ubuntu-latest
    env:
      BACKEND_DIR: ./backend
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/poetry-python-install
        name: Install Python, poetry and Python dependencies
        with:
          poetry-install-args: --with tests --with mypy --with custom-data --no-root
          poetry-working-directory: ${{ env.BACKEND_DIR }}
      - name: Run Mypy
        run: poetry run mypy chainlit/
        working-directory: ${{ env.BACKEND_DIR }}
