name: Mypy

on: [workflow_call]

jobs:
  mypy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install --with tests --with mypy --with custom-data
      - name: Create mypy.ini
        run: |
          echo "[mypy]" > mypy.ini
          echo "ignore_missing_imports = True" >> mypy.ini
      - name: Run Mypy
        run: poetry run mypy chainlit/
