name: Mypy

on: [workflow_call]

jobs:
  mypy:
    runs-on: ubuntu-latest
    env:
      BACKEND_DIR: ./backend
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/poetry-python-install
        name: Install Python, poetry and Python dependencies
        with:
          python-version: 3.9
          poetry-version: 1.8.3
          poetry-install-args: --with tests --with mypy --with custom-data
          poetry-working-directory: ${{ env.BACKEND_DIR }}
      - name: Run Mypy
        run: poetry run mypy chainlit/
        working-directory: ${{ env.BACKEND_DIR }}
