name: Mypy

on: [workflow_call]

jobs:
  mypy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          cache: "pip"
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install --with tests --with mypy --with custom-data
      - name: Run Mypy
        run: poetry run mypy chainlit/
