name: Pytest

on: [workflow_call]

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']
    env:
      BACKEND_DIR: ./backend
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/poetry-python-install
        name: Install Python, poetry and Python dependencies
        with:
          python-version: ${{ matrix.python-version }}
          poetry-version: 1.8.3
          poetry-install-args: --with tests --with mypy --with custom-data
          poetry-working-directory: ${{ env.BACKEND_DIR }}
      - name: Run Pytest
        run: poetry run pytest --cov=chainlit/
        working-directory: ${{ env.BACKEND_DIR }}
