name: Pytest

on: [workflow_call]

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install --with tests --with mypy --with custom-data
      - name: Run Pytest
        run: poetry run pytest --cov=chainlit/
