name: Pytest

on: [workflow_call]

permissions: read-all

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
        fastapi-version: ['0.115']
    env:
      BACKEND_DIR: ./backend
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm-node-install
        name: Install Node, pnpm and dependencies.
      - uses: ./.github/actions/uv-python-install
        name: Install Python, uv and Python dependencies
        with:
          python-version: ${{ matrix.python-version }}
          working-directory: ${{ env.BACKEND_DIR }}
          extra-install-args: .[tests,mypy,custom-data]
      - name: Install fastapi ${{ matrix.fastapi-version }}
        run: uv add fastapi --version ^${{ matrix.fastapi-version}}
        working-directory: ${{ env.BACKEND_DIR }}
      - name: Run Pytest
        run: uv run pytest --cov=chainlit/
        working-directory: ${{ env.BACKEND_DIR }}
